REM This build.bat was generated by chatgpt. It was prompted with a
REM hand-created Makefile and asked to generate a .bat file that
REM would behave the same as the Makefile in a windows environment.
REM It's contents have been human-audited.

@echo off
setlocal

set "CFLAGS=/std:c17 /Iinclude /W4 /WX /permissive-"
set "BIN=bin"

if "%1"=="" goto win64
if /I "%1"=="win64" goto win64
if /I "%1"=="sdl" goto sdl
if /I "%1"=="run-demo" goto run_demo
if /I "%1"=="run-demo-sdl" goto run_demo_sdl
if /I "%1"=="clean" goto clean

echo Usage: build.bat [win64^|sdl^|run-demo^|run-demo-sdl^|clean]
exit /b 1

:win64
if not exist "%BIN%" mkdir "%BIN%"
cl %CFLAGS% /Fe:"%BIN%\vt7_pt_demo_win64.exe" ^
    src\vt7_pt_win64.c ^
    src\vt7_pt_demo.c
exit /b %ERRORLEVEL%

:sdl
if not exist "%BIN%" mkdir "%BIN%"
cl %CFLAGS% /Fe:"%BIN%\vt7_pt_demo_sdl.exe" ^
    src\vt7_pt_sdl.c ^
    src\vt7_pt_demo.c ^
    /link SDL3.lib
exit /b %ERRORLEVEL%

:run_demo
call "%~f0" win64
if errorlevel 1 exit /b 1
"%BIN%\vt7_pt_demo_win64.exe"
exit /b %ERRORLEVEL%

:run_demo_sdl
call "%~f0" sdl
if errorlevel 1 exit /b 1
"%BIN%\vt7_pt_demo_sdl.exe"
exit /b %ERRORLEVEL%

:clean
if exist "%BIN%" rmdir /s /q "%BIN%"
exit /b 0
